# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13.0-rc.1"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Lint with flake8
      run: |
        flake8 hw2/hw2_debugging.py hw2/rand.py > post_traces/flake8_trace.txt

    - name: Lint with pylint
      run: |
        pylint hw2/hw2_debugging.py hw2/rand.py > post_traces/pylint_trace.txt

    - name: Static analysis with bandit
      run: |
        bandit hw2/hw2_debugging.py hw2/rand.py > post_traces/bandit_trace_fixed.txt

    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest hw2/test_hw2.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: UXCNOWHH2O
        files: ./coverage.xml
        flags: unittests
        name: codecov-coverage
        fail_ci_if_error: true
