# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # - name: Install Python 3.13 manually
    #   run: |
    #     sudo apt update -y
    #     sudo apt upgrade -y
    #     sudo apt install software-properties-common -y
    #     sudo add-apt-repository ppa:deadsnakes/ppa -y
    #     sudo apt update -y
    #     sudo apt install python3.13 -y
    #     sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.13 1
    # - name: Install distutils using pip
    #   run: |
    #     python3 -m ensurepip --upgrade
    #     python3 -m pip install setuptools
    # - name: Verify Python 3.13 installation
    #   run: python3 --version
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest test_hw1a.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: UXCNOWHH2O
        files: ./coverage.xml
        flags: unittests
        name: codecov-coverage
        fail_ci_if_error: true
